sudo: required
services:
    -  docker

before_install:
    -  docker build -t gaddiego/docker-react -f Dockerfile.dev .

script:
    -   docker run -e CI=true gaddiego/docker-react npm run test
    
#deploy:
#    provider: elasticbeanstalk
#    region: "eu-north-1"
#    app: "frontendv1"
#    env: "Frontendv1-env"
#    bucket_name: "elasticbeanstalk-eu-north-1-108782091232"
#    bucket_path: "frontendv1"
#    on:
#        branch: master
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: "$AWS_SECRET_KEY"